/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.ControllerProntoSocorro;
import model.ProntoSocorro;
/**
 *
 * @author João Victor
 */
public class EditarProntoSocorro extends javax.swing.JFrame {
  private ControllerProntoSocorro cps = new ControllerProntoSocorro();
    private int idProntoSocorro;

    /**
     * Creates new form EditarHospital
     */
    public EditarProntoSocorro() {
        initComponents();
        
        atualizarListaProntoSocorro();
    }
    
    private void atualizarListaProntoSocorro(){
        cmbProntoSocorro.removeAllItems();
        
        for(ProntoSocorro ps : cps.listarProntoSocorro()){
        //    cmbProntoSocorro.addItem(h);
        }
    }
    
    private void habilitarCampos(){
        txt_endereco_prontoSocorro.setVisible(true);
    }
    
    private void desabilitarCampos(){
        txt_endereco_prontoSocorro.setVisible(false);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        desabilitarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txt_endereco_prontoSocorro = new javax.swing.JTextField();
        btn_cadastrar_prontoSocorro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbProntoSocorro = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txt_endereco_prontoSocorro1 = new javax.swing.JTextField();
        btn_editar_prontoSocorro = new javax.swing.JButton();
        btn_calcelarEdicao_ProntoSocorro = new javax.swing.JButton();
        btn_excluir_ProntoSocorro = new javax.swing.JButton();
        btn_salvar_ProntoSocorro = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Hospital:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Pronto Socorro");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Endereço:");

        btn_cadastrar_prontoSocorro.setText("Cadastrar");
        btn_cadastrar_prontoSocorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_prontoSocorroActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Hospital:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Editar Pronto Socorro");

        cmbProntoSocorro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProntoSocorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProntoSocorroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Endereço:");

        btn_editar_prontoSocorro.setText("Editar");
        btn_editar_prontoSocorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_prontoSocorroActionPerformed(evt);
            }
        });

        btn_calcelarEdicao_ProntoSocorro.setText("Cancelar");
        btn_calcelarEdicao_ProntoSocorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcelarEdicao_ProntoSocorroActionPerformed(evt);
            }
        });

        btn_excluir_ProntoSocorro.setText("Excluir");
        btn_excluir_ProntoSocorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_ProntoSocorroActionPerformed(evt);
            }
        });

        btn_salvar_ProntoSocorro.setText("Salvar");
        btn_salvar_ProntoSocorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_ProntoSocorroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_editar_prontoSocorro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_calcelarEdicao_ProntoSocorro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_excluir_ProntoSocorro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar_ProntoSocorro))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(cmbProntoSocorro, 0, 329, Short.MAX_VALUE)
                        .addComponent(txt_endereco_prontoSocorro1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbProntoSocorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_endereco_prontoSocorro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar_prontoSocorro)
                    .addComponent(btn_calcelarEdicao_ProntoSocorro)
                    .addComponent(btn_excluir_ProntoSocorro)
                    .addComponent(btn_salvar_ProntoSocorro))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        ControllerProntoSocorro cps = new ControllerProntoSocorro();
        cmbProntoSocorro.removeAllItems();

        for(ProntoSocorro ps : cps.listarProntoSocorro()){
            cmbProntoSocorro.addItem(ps);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_cadastrar_prontoSocorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_prontoSocorroActionPerformed
       /* ProntoSocorro ps = (ProntoSocorro)cmbProntoSocorro.getSelectedItem();
        JOptionPane.showMessageDialog(rootPane, ps.getIdHospital()); */
    }//GEN-LAST:event_btn_cadastrar_prontoSocorroActionPerformed

    private void cmbProntoSocorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProntoSocorroActionPerformed
        ControllerProntoSocorro cps = new ControllerProntoSocorro();
        cmbProntoSocorro.removeAllItems();

        for(ProntoSocorro ps : cps.listarProntoSocorro()){
            cmbProntoSocorro.addItem(ps);
        }
    }//GEN-LAST:event_cmbProntoSocorroActionPerformed

    private void btn_editar_prontoSocorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_prontoSocorroActionPerformed
        int i = cmbProntoSocorro.getSelectedIndex();
        /* ProntoSocorro ps = (ProntoSocorro) cmbProntoSocorro.getItemAt(i);
        txt_endereco_prontoSocorro.setText(f.getEndereco());
        cmbProntoSocorro.getItemCount(f.getIdFilial);

        idProntoSocorro = ps.getIdProntoSocorro(); */

        habilitarCampos();
    }//GEN-LAST:event_btn_editar_prontoSocorroActionPerformed

    private void btn_calcelarEdicao_ProntoSocorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcelarEdicao_ProntoSocorroActionPerformed
        desabilitarCampos();
    }//GEN-LAST:event_btn_calcelarEdicao_ProntoSocorroActionPerformed

    private void btn_excluir_ProntoSocorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_ProntoSocorroActionPerformed
      //  cps.deletar(idProntoSocorro);

        atualizarListaProntoSocorro();

        desabilitarCampos();
    }//GEN-LAST:event_btn_excluir_ProntoSocorroActionPerformed

    private void btn_salvar_ProntoSocorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_ProntoSocorroActionPerformed
     /*   ProntoSocorro ps = new ProntoSocorro(txt_endereco_prontoSocorro.getText());
        

        cf.atualizar(f);

        atualizarListaFuncionario();

        desabilitarCampos();*/
    }//GEN-LAST:event_btn_salvar_ProntoSocorroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProntoSocorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProntoSocorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProntoSocorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProntoSocorro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProntoSocorro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_prontoSocorro;
    private javax.swing.JButton btn_calcelarEdicao_ProntoSocorro;
    private javax.swing.JButton btn_editar_prontoSocorro;
    private javax.swing.JButton btn_excluir_ProntoSocorro;
    private javax.swing.JButton btn_salvar_ProntoSocorro;
    private javax.swing.JComboBox cmbProntoSocorro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_endereco_prontoSocorro;
    private javax.swing.JTextField txt_endereco_prontoSocorro1;
    // End of variables declaration//GEN-END:variables
}
